export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
